name: sphinx-documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  publish-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.1.1
        with:
          python-version: 3.12
          cache: pip
      - run: pip install .
      - run: pip install sphinx sphinx_rtd_theme
      - run: sphinx-build doc/source doc/build
      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/build
          force_orphan: true
